### ISSUE TITLE
Netbeans 6.9.1 compatibility?

### ISSUE THREAD

**Issue by igrigorik** [ericthorsen/enclojure#10]
Hey, trying to install enclojure on 6.9.1, and unfortunately the plugin is not getting picked up by NB. Noticed that you just pushed out 1.4.0, but no downloadable .nbm.. Tried checking out the repo and building, but looks like I'm missing some deps. 

Long story short, will it/can it work on 6.9.1? And if so, then how does one go about getting that up and running?

ig

**Comment by ThorTech** [comment]
Did you follow the instructions on:
www.enclojure.org 
I installed 6.9.1, followed the instructions and it works like a charm.
Let me know,
Eric

**Comment by igrigorik** [comment]
_face palm_ don't mind me :-)

So used to downloading .nbm's to install a plugin that I completely glossed over those instructions. Worked as advertised. Thanks for your help!

ig
